"""add table projects V4

Revision ID: 41ce6d3f453b
Revises: 4f746e379b65
Create Date: 2026-07-04 18:47:07.773590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ce6d3f453b'
down_revision: Union[str, Sequence[str], None] = '4f746e379b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_projects', 'projects', ['project_id'], ['id'])
    op.drop_column('user_projects', 'project_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.drop_column('user_projects', 'project_id')
    # ### end Alembic commands ###
