"""add table projects V3

Revision ID: 4f746e379b65
Revises: aad91cae22e6
Create Date: 2026-07-04 18:23:41.646863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f746e379b65'
down_revision: Union[str, Sequence[str], None] = 'aad91cae22e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('projects', 'descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
